# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  #push:
  #  branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Maven Build
        run: mvn clean package -DskipTests
        
      - name: Install SAST Rapid Scan
        run: |
          curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE -o /tmp/sigma $COV_URL/downloadFile.htm?fn=sigma
          chmod +x /tmp/sigma
          
      - name: Rapid Scan (SAST)
        run: |
          /tmp/sigma analyze --format JSON .
          cat sigma-results.json
        
        
      - name: Rapid Scan (SCA)
        uses: blackducksoftware/github-action@v2.2
        with:
          version: 7
          blackduck.url: ${{ secrets.BLACKDUCK_URL }}
          blackduck.api.token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          args: >
            --detect.blackduck.scan.mode=RAPID
            --detect.policy.check.fail.on.severities="BLOCKER"
